config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :accounts do
    resources :transactions
    member do
      post 'withdraw'
      post 'deposit'
      post 'verify_pin'
      post 'send_money'
      post 'change_status'
    end
  end

  root 'home#index'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/account.rb
class Account < ApplicationRecord

  CURRENCIES = ['PKR', 'USD', 'SAR'].freeze

  enum status: {
    active: 1,
    blocked: 2
  }, _default: :active

  belongs_to :user
  has_many :transactions, dependent: :destroy

  validates :pin, presence: true, format: { with: /\A\d{4}\z/, message: 'Must be exactly 4 digits' }
  validates :balance, presence: true, numericality: true
  validates :currency, presence: true, inclusion: { in: CURRENCIES }

  def valid_transfer?(recipient, amount)
    sufficient_balance?(amount) && recipient&.currency == currency && recipient&.active?
  end

  def sufficient_balance?(amount)
    amount <= balance
  end

  def give_notice(recipient, amount)
    if !recipient
      'Account does not exist'
    elsif !sufficient_balance?(amount)
      'Insufficient Balance'
    elsif recipient.currency != currency
      'Cannot transfer to different currency'
    elsif recipient.blocked?
      'Cannot transfer to blocked account'
    end
  end

  def create_transaction(amount, type, account = self)
    account.transactions.create!(user: account.user, amount:, transaction_type: Transaction.transaction_types[type])
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account
  belongs_to :user

  enum transaction_type: {
    withdraw: 1,
    deposit: 2,
    send_money: 3,
    received_money: 4
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :accounts, dependent: :destroy
  has_many :transactions, through: :accounts, dependent: :destroy
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  include AccountConcern
  before_action :set_account, except: [:index, :create, :new]
  before_action :authorize_account, except: [:index, :create, :new]

  def index
    @accounts = current_user.accounts.paginate(page: params[:page], per_page: 3)
    return unless params[:form_type].eql?('verify_pin') && params[:account_id]

    @account = Account.find_by(id: params[:account_id])
  end

  def new
    @account = current_user.accounts.build(status: :active)
  end

  def create
    @account = current_user.accounts.build(account_params)
    if @account.save
      redirect_to @account
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @account.update(account_params) ? redirect_to(@account) : render(:edit, status: :unprocessable_entity)
  end

  def destroy
    if @account.destroy
      redirect_to accounts_path, notice: 'Account deleted successfully'
    else
      redirect_to accounts_path, notice: 'Problem deleting account'
    end
  end

  def change_status
    new_status = @account.active? ? :blocked : :active
    @account.update(status: new_status)
    redirect_to @account
  end

  def withdraw
    amount = params[:amount].to_f

    ActiveRecord::Base.transaction do
      @account.lock!
      if @account.sufficient_balance?(amount)
        @account.update(balance: @account.balance - amount)
        @account.create_transaction(amount, :withdraw)
        redirect_to @account, notice: 'Withdrawal successful'
      else
        flash[:alert] = 'Insufficient balance'
        redirect_to @account
      end
    end
  rescue ActiveRecord::StaleObjectError, ActiveRecord::RecordInvalid
    flash[:alert] = 'Transaction failed. Please try again.'
    redirect_to @account
  end

  def deposit
    amount = params[:amount].to_f
    return unless amount.positive?

    ActiveRecord::Base.transaction do
      @account.lock!
      @account.update!(balance: @account.balance + amount)
      @account.create_transaction(amount, :deposit)
      redirect_to @account, notice: 'Deposit successful'
    end
  rescue ActiveRecord::StaleObjectError, ActiveRecord::RecordInvalid
    flash[:alert] = 'Transaction failed. Please try again.'
    redirect_to @account
  end

  def verify_pin
    if @account.pin == params[:pin]
      redirect_to @account
    else
      flash[:alert] = 'Invalid PIN'
      redirect_to accounts_path(form_type: 'verify_pin', account_id: params[:account_id])
    end
  end

  def send_money
    amount = params[:amount].to_f
    recipient = find_account(params[:recipient_account_id])
    ActiveRecord::Base.transaction do
      @account.lock!
      recipient.lock!
      if @account.valid_transfer?(recipient, amount)
        recipient.update(balance: recipient.balance + amount)
        @account.update(balance: @account.balance - amount)

        @account.create_transaction(amount, :send_money)
        @account.create_transaction(amount, :received_money, recipient)
        redirect_to @account, notice: 'Money Transferred'
      else
        redirect_to @account, notice: @account.give_notice(recipient, amount)
      end
    end
  rescue ActiveRecord::StaleObjectError, ActiveRecord::RecordInvalid
    flash[:alert] = 'Transaction failed. Please try again.'
    redirect_to @account
  end

  private

  def authorize_account
    return if @account.user == current_user

    redirect_to accounts_path, status: :unauthorized
  end

  def account_params
    params.require(:account).permit(:pin, :balance, :status, :currency)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :validate_page_param
  rescue_from ActiveRecord::RecordNotFound, with: :render_not_found

  def render_not_found
    render file: "#{Rails.root}/public/404.html", layout: 'not_found', status: :not_found
  end

  def validate_page_param
    params[:page] = params[:page].to_i < 1 ? 1 : params[:page]
  end
end

app/controllers/concerns/account_concern.rb
module AccountConcern
  extend ActiveSupport::Concern

  def set_account
    @account = Account.find(params[:id] || params[:account_id])
    redirect_to accounts_path, notice: 'Account not found' unless @account
  end

  def find_account(account_id)
    Account.find(account_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  include AccountConcern
  before_action :set_account

  def index
    @transactions = @account.transactions
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/views/accounts/_deposit_form.html.erb
<%= form_with url: deposit_account_path(@account), method: :post, local: true do |form| %>
  <div>
    <%= form.label :amount, "Amount to deposit" %><br>
    <%= form.number_field :amount, step: 0.01 %>
  </div>
  <br>
  <div>
    <%= form.submit 'Deposit' %>
  </div>
<% end %>

app/views/accounts/_send_money_form.html.erb
<%= form_with url: send_money_account_path(@account), method: :post, local: true do |form| %>
    <div>
        <%= form.label :recipient_account_id, "Enter Recipient Account Number" %><br>
        <%= form.text_field :recipient_account_id %>
    </div>
<br>
    <div>
        <%= form.label :amount, "Enter Amount" %><br>
        <%= form.number_field :amount %>
    </div>
<br>
    <div>
        <%= form.submit "Transfer" %>
    </div>
<% end %>

app/views/accounts/_verify_pin_form.html.erb
<%= form_with url: verify_pin_account_path(@account), method: :post, local: true do |form| %>
  <div>
    <%= form.label :pin, "Enter PIN" %><br>
    <%= form.password_field :pin %>
  </div>
  <br>
  <div>
    <%= form.submit "Verify PIN" %>
  </div>
<% end %>

app/views/accounts/_withdraw_form.html.erb
<%= form_with url: withdraw_account_path(@account), method: :post, local: true do |form| %>
  <div>
    <%= form.label :amount, "Amount to withdraw" %><br>
    <%= form.number_field :amount, step: 0.01 %>
  </div>
  <br>
  <div>
    <%= form.submit 'Withdraw' %>
  </div>
<% end %>

app/views/accounts/index.html.erb
<h1>Welcome <%= current_user.email %></h1>
<%= link_to 'Create Account', new_account_path %>
<h2>Here are your accounts</h2>

<% if @accounts.empty? %>
  <p>No accounts to display. Please create one.</p>
<% else %>
  <ul>
    <% @accounts.each do |account| %>
      <li>
        <%= link_to "Account ##{account.id}", accounts_path(form_type: 'verify_pin', account_id: account.id) %>
        <p>Currency: <%= account.currency %> | Balance: <%= account.balance %></p>
      </li>
    <% end %>
  </ul>
  <p><%= link_to 'Back', root_path %></p>
<% end %>
<br>
<br>
<%= will_paginate @accounts %>

<% if params[:form_type] == 'verify_pin' %>
  <% if @account %>
    <%= render 'verify_pin_form', account: @account %>
  <% else %>
    <p>Account not found.</p>
  <% end %>
<% end %>

app/views/accounts/new.html.erb
<h1> New Account </h1>
<%= form_with model: @account, local: true do |form| %>
    <div>
        <%= form.label :pin %>
        <%= form.number_field :pin %>
        <% @account.errors.full_messages_for(:pin).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <br>
    <div>
        <%= form.label :currency %>
        <%= form.select :currency, Account::CURRENCIES, selected: @account.currency || 'PKR'%>
    </div>

    <br>

    <%= form.number_field :balance, value: 0, type: :hidden%>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/accounts/send_money.html.erb
<h1> Send Money </h1>

<%= form_with url: send_money_account_path(@account), method: :post, local: true do |form| %>
    <div>
        <%= form.label :recipient_account, "Enter Recipient Account Number" %><br>
        <%= form.text_field :recipient_account %>
    </div>
<br>
    <div>
        <%= form.label :amount, "Enter Amount" %><br>
        <%= form.number_field :amount %>
    </div>
<br>
    <div>
        <%= form.submit "Transfer" %>
    </div>
<% end %>

app/views/accounts/show.html.erb
<h1>Account Details</h1>
<p>Account Number: <%= @account.id %></p>
<p>Balance: <%= @account.balance %></p>
<p>Currency: <%= @account.currency %></p>
<p>Status: <%= @account.status.humanize %></p>

<% if @account.active? %>
  <%= link_to 'Withdraw', account_path(@account, form_type: 'withdraw') %>
  <br>
  <%= link_to 'Deposit', account_path(@account, form_type: 'deposit') %>
  <br>
  <%= link_to 'Send Money', account_path(@account, form_type: 'send_money') %>
  <br>
  <br>
<% end %>
<%= link_to 'Transaction History', account_transactions_path(@account) %>
<br>
<br>
<%= button_to 'Delete Account', account_path(@account), method: :delete %>
<% if @account.active? %>
  <%= button_to 'Block Account', change_status_account_path(@account) %>
<% else %>
  <%= button_to 'Activate Account', change_status_account_path(@account) %>
<% end %>
<br>
<%= link_to 'Back', accounts_path %>

<% case params[:form_type] %>
<% when 'withdraw' %>
  <%= render 'withdraw_form' %>
<% when 'deposit' %>
  <%= render 'deposit_form' %>
<% when 'send_money' %>
  <%= render 'send_money_form' %>
<% when 'verify_pin' %>
<% end %>

app/views/accounts/verify_pin.html.erb
<h1>Verify PIN for Account <%= @account.account_number %></h1>

<%= form_with url: verify_pin_account_path(@account), method: :post, local: true do |form| %>
  <div>
    <%= form.label :pin, "Enter PIN" %><br>
    <%= form.password_field :pin %>
  </div>
  <br>
  <div>
    <%= form.submit "Verify PIN" %>
  </div>
<% end %>

app/views/home/index.html.erb
<h1>ATM Application</h1>

<% if user_signed_in? %>
    <%= button_to 'Sign Out', destroy_user_session_path, method: :delete%>
    <%= button_to 'View Accounts', accounts_path, method: :get%>
<% else %>
    <%= button_to 'Sign In', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Atm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/not_found.html.erb
<h1> 404: Not Found </h1>
<%= link_to 'Back to home', root_path %>

app/views/layouts/unauthorized.html.erb
<h1>Sorry you don't have access for that </h2>
<%= link_to 'Go back', accounts_path %>

app/views/transactions/_transaction.html.erb
<tr>
    <td><%= transaction.amount %></td>
    <td><%= transaction.transaction_type.humanize %></td>
    <td><%= transaction.created_at %></td>
</tr>

app/views/transactions/index.html.erb
<h1>Transactions for Account <%= @account.id %></h1>
<% if @transactions.any? %>
  <table>
    <thead>
      <tr>
        <th>Amount</th>
        <th>Type</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
    <%= render @transactions %>
    </tbody>
  </table>
<% else %>
  <p>No transactions found.</p>
<% end %>
<br>
<%= link_to 'Back', @account %> 